### ISSUE TITLE
Producing the erocci/erocci image automatically

### ISSUE THREAD

**Issue by philippemerle** [erocci/docker-erocci#2]
The current erocci/erocci image is an old image generated from an old erocci code.
erocci/erocci image should be regenerated from last erocci code base.
Perhaps, this should be added to the continuous integration of erocci in order to do continuous delivery of the erocci Docker image.

**Comment by jeanparpaillon** [comment]
Docker image has been updated to latest erocci
COMMIT_ID file contains the git id of the erocci version
Updating this file trigger a new build, available here:
https://hub.docker.com/r/jeanparpaillon/erocci/
